# SQUARE PREDICTION

In [1]:
# IMPORTING PYTHON LIBRARIES (NUMPY,PANDAS,MATPLOTLIB,SEABORN,sklearn) :
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
#Importing dataset : 
dataset=pd.read_csv("square.csv")
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x350,300x400,300x450,250x250,3,3,675
1,300x320,300x400,300x450,250x250,3,3,675
2,300x300,300x400,300x450,250x250,3,3,675
3,300x300,300x350,300x450,250x250,3,3,675
4,300x300,300x320,300x450,250x250,3,3,675
...,...,...,...,...,...,...,...
1279,350x420,350x470,350x600,250x400,5,9,3600
1280,350x410,350x460,350x600,250x400,5,9,3600
1281,350x400,350x440,350x600,250x400,5,9,3600
1282,350x400,350x430,350x600,250x400,5,9,3600
1283,350x400,350x420,350x600,250x400,5,9,3600

In [3]:
# DISPLAYING INFORMATIONS ABOUT DATASET
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Corner column(o/p)  1284 non-null   object
 1   Outer column(o/p)   1284 non-null   object
 2   Inner Column(o/p)   1284 non-null   object
 3   Beam(o/p)           1284 non-null   object
 4   Span(i/p)           1284 non-null   int64
 5   Storey(i/p)         1284 non-null   int64
 6   Area(sqm)(i/p)      1284 non-null   int64
dtypes: int64(3), object(4)
memory usage: 70.3+ KB

In [4]:
# DESCRIBING DATASET( COUNT , MEAN , MINIMUM ,MAXIMUM ,...)
dataset.describe()

         Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
count  1284.000000  1284.000000     1284.000000
mean      3.760125     6.906542     1860.626168
std       0.737651     2.076627      747.091606
min       3.000000     3.000000      675.000000
25%       3.000000     6.000000     1350.000000
50%       4.000000     7.000000     1800.000000
75%       4.000000     9.000000     2048.000000
max       5.000000     9.000000     3600.000000

In [5]:
# DISPLAYING SHAPE OF DATASET( NUMBER OF ROWS AND COLUMNS )
print("numder of rows and columns in the dataset is : ",dataset.shape)

numder of rows and columns in the dataset is :  (1284, 7)

In [6]:
# DISPLAYING NUMBER OF ROWS ONLY
print("numder of rows is : ",dataset.shape[0])

numder of rows is :  1284

In [7]:
# DISPLAYING NUMBER OF COLUMNS ONLY
print("numder of rows is : ",dataset.shape[1])

numder of rows is :  7

In [8]:
# DISPLAYING COLUMNS OF THE DATASET( COLUMN NAMES )
dataset.columns

Index(['Corner column(o/p)', 'Outer column(o/p)', 'Inner Column(o/p)',
       'Beam(o/p)', 'Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)'],
      dtype='object')

In [9]:
# DISPLAYING FIRST 10 ROWS OF THE DATASET USING HEAD METHOD
dataset.head(10)

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x350,300x400,300x450,250x250,3,3,675
1,300x320,300x400,300x450,250x250,3,3,675
2,300x300,300x400,300x450,250x250,3,3,675
3,300x300,300x350,300x450,250x250,3,3,675
4,300x300,300x320,300x450,250x250,3,3,675
5,300x300,300x300,300x400,250x250,3,3,675
6,300x300,300x300,300x350,250x250,3,3,675
7,300x300,300x300,300x300,250x250,3,3,675
8,300x340,300x390,300x440,250x250,3,3,675
9,300x330,300x380,300x430,250x250,3,3,675

In [10]:
# DISPLAYING LAST 10 ROWS OF THE DATASET USING TAIL METHOD
dataset.tail(10)

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
1274,350x480,350x530,350x600,250x400,5,9,3600
1275,350x470,350x520,350x600,250x400,5,9,3600
1276,350x460,350x510,350x600,250x400,5,9,3600
1277,350x440,350x490,350x600,250x400,5,9,3600
1278,350x430,350x480,350x600,250x400,5,9,3600
1279,350x420,350x470,350x600,250x400,5,9,3600
1280,350x410,350x460,350x600,250x400,5,9,3600
1281,350x400,350x440,350x600,250x400,5,9,3600
1282,350x400,350x430,350x600,250x400,5,9,3600
1283,350x400,350x420,350x600,250x400,5,9,3600

In [11]:
# DISPLAYING MINIMUM VALUES OF ALL COLUMNS 
dataset.min()

Corner column(o/p)    300x300
Outer column(o/p)     300x300
Inner Column(o/p)     300x300
Beam(o/p)             250X350
Span(i/p)                   3
Storey(i/p)                 3
Area(sqm)(i/p)            675
dtype: object

In [12]:
# DISPLAYING MAXIMUM VALUES OF ALL COLUMNS
dataset.max()

Corner column(o/p)    380x690
Outer column(o/p)     380x640
Inner Column(o/p)     600x650
Beam(o/p)             250x450
Span(i/p)                   5
Storey(i/p)                 9
Area(sqm)(i/p)           3600
dtype: object

In [13]:
# SORTING USING INDEX
print("sorted data using index number \n\n ",dataset.sort_index)

sorted data using index number

  <bound method DataFrame.sort_index of      Corner column(o/p) Outer column(o/p) Inner Column(o/p) Beam(o/p)  \
0               300x350           300x400           300x450   250x250
1               300x320           300x400           300x450   250x250
2               300x300           300x400           300x450   250x250
3               300x300           300x350           300x450   250x250
4               300x300           300x320           300x450   250x250
...                 ...               ...               ...       ...
1279            350x420           350x470           350x600   250x400
1280            350x410           350x460           350x600   250x400
1281            350x400           350x440           350x600   250x400
1282            350x400           350x430           350x600   250x400
1283            350x400           350x420           350x600   250x400

      Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
0             3            3             675
1             3            3             675
2             3            3             675
3             3            3             675
4             3            3             675
...         ...          ...             ...
1279          5            9            3600
1280          5            9            3600
1281          5            9            3600
1282          5            9            3600
1283          5            9            3600

[1284 rows x 7 columns]>

In [14]:
# DISPLAY COUNTS OF EACH VALUES OF SPECIFIED COLUMN

In [15]:
dataset["Corner column(o/p)"].value_counts()

300x320    68
300x350    56
350X350    36
300x300    36
300x340    32
           ..
350x670     4
350x680     4
350x690     4
350x700     4
380X350     4
Name: Corner column(o/p), Length: 107, dtype: int64

In [16]:
#  FINDING NULL VALUES IN THE DATASET
print ( "NULL VALUES : \n" , dataset . isnull())

NULL VALUES :
       Corner column(o/p)  Outer column(o/p)  Inner Column(o/p)  Beam(o/p)  \
0                  False              False              False      False
1                  False              False              False      False
2                  False              False              False      False
3                  False              False              False      False
4                  False              False              False      False
...                  ...                ...                ...        ...
1279               False              False              False      False
1280               False              False              False      False
1281               False              False              False      False
1282               False              False              False      False
1283               False              False              False      False

      Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
0         False        False           False
1         False        False           False
2         False        False           False
3         False        False           False
4         False        False           False
...         ...          ...             ...
1279      False        False           False
1280      False        False           False
1281      False        False           False
1282      False        False           False
1283      False        False           False

[1284 rows x 7 columns]

In [17]:
#checking duplicate values
print(dataset.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
1279     True
1280     True
1281     True
1282     True
1283     True
Length: 1284, dtype: bool

In [18]:
#dropping duplicate values
dataset.drop_duplicates(inplace=True)
print(dataset.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
316    False
317    False
318    False
319    False
320    False
Length: 319, dtype: bool

In [19]:
#Corner column
x=dataset.iloc[:,4:].values
y=dataset.iloc[:,0].values

In [20]:
x

array([[   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600]], dtype=int64)

In [21]:
x = x.astype('i')
x

array([[   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   3,    3,  675],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   4,    3,  768],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   5,    3, 1200],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    5, 1125],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   3,    6, 1350],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   4,    6, 1536],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   5,    6, 2400],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   3,    7, 1575],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   4,    7, 1792],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   3,    8, 1800],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   4,    8, 2048],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   3,    9, 2025],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   4,    9, 2304],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600],
       [   5,    9, 3600]], dtype=int32)

In [22]:
y

array(['300x350', '300x320', '300x300', '300x300', '300x300', '300x300',
       '300x300', '300x300', '300x340', '300x330', '300x310', '300x340',
       '300x340', '300x340', '300x340', '300x340', '300x320', '300x320',
       '300x320', '300x320', '300x320', '300x350', '300x300', '300x300',
       '300x300', '300x340', '300x330', '300x320', '300x310', '300x320',
       '300x320', '300x320', '300x320', '300x320', '300x320', '300x320',
       '300x320', '300x320', '300x320', '350x350', '350x300', '350x300',
       '350x300', '350x300', '350x340', '350x330', '350x320', '350x310',
       '350x310', '350x320', '350x320', '350x310', '350x450', '350x350',
       '350x440', '350x430', '350x420', '350x410', '350x400', '350x390',
       '350x380', '350x370', '350x360', '350x350', '350x360', '350x370',
       '350x350', '350x360', '350x450', '350x400', '350x350', '350x350',
       '350x350', '350x360', '350x370', '300x380', '300x390', '300x410',
       '300x420', '300x430', '300x440', '350X450', '350X400', '350X350',
       '350X350', '350X350', '350X350', '350x440', '350x430', '350x420',
       '350x410', '350x390', '350x380', '350x370', '350x360', '350X450',
       '350X400', '350X350', '350X350', '350X350', '350x440', '350x430',
       '350x420', '350x410', '350x390', '350x380', '350x370', '350x360',
       '300x550', '300x350', '300x540', '300x530', '300x520', '300x510',
       '300x500', '300x490', '300x480', '300x470', '300x460', '300x450',
       '300x440', '300x430', '300x420', '300x410', '300x400', '300x390',
       '300x380', '300x370', '300x360', '300x350', '300x340', '300x350',
       '300x350', '300x360', '350x650', '350x400', '350x640', '350x630',
       '350x620', '350x610', '350x600', '350x590', '350x580', '350x570',
       '350x560', '350x550', '350x540', '350x530', '350x520', '350x510',
       '350x500', '350x490', '350x480', '350x470', '350x460', '350x450',
       '350x440', '350x430', '350x420', '350x410', '350x400', '350x410',
       '350x390', '350x400', '350x390', '300x600', '300x400', '300x590',
       '300x580', '300x570', '300x560', '300x550', '300x540', '300x530',
       '300x520', '300x510', '300x500', '300x490', '300x480', '300x470',
       '300x460', '300x450', '300x440', '300x430', '300x420', '300x410',
       '300x400', '300x390', '300x380', '300x390', '350x700', '350x450',
       '350x690', '350x680', '350x670', '350x660', '350x650', '350x640',
       '350x630', '350x620', '350x610', '350x600', '350x590', '350x580',
       '350x570', '350x560', '350x550', '350x540', '350x530', '350x520',
       '350x510', '350x500', '350x490', '350x480', '350x470', '350x460',
       '350x450', '350x460', '350x440', '350x460', '350x450', '300x600',
       '300x550', '300x500', '300x450', '300x400', '300x350', '300x350',
       '300x350', '300x350', '300x350', '300x350', '300x350', '300x350',
       '300x590', '300x580', '300x570', '300x560', '300x540', '300x530',
       '300x520', '300x510', '300x490', '300x480', '300x470', '300x460',
       '300x440', '300x430', '300x420', '300x410', '300x390', '300x380',
       '300x370', '300x360', '300x360', '380X700', '380X650', '380X600',
       '380X550', '380X500', '380X450', '380X500', '380X400', '380X400',
       '380x690', '380x680', '380x670', '380x660', '380x640', '380x630',
       '380x620', '380x610', '380x590', '380x580', '380x570', '380x560',
       '380x540', '380x530', '380x520', '380x510', '380x490', '380x480',
       '380x470', '380x460', '380x440', '380x430', '380x420', '380x410',
       '380X600', '380X550', '380X500', '380X450', '380X400', '380X350',
       '350X400', '350X400', '350X400', '350X400', '350X400', '350X400',
       '380x590', '380x580', '380x570', '380x560', '350x540', '350x530',
       '350x520', '350x510', '350x490', '350x480', '350x470', '350x460',
       '350x440', '350x430', '350x420', '350x410', '350x400', '350x400',
       '350x400'], dtype=object)

In [23]:
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x350,300x400,300x450,250x250,3,3,675
1,300x320,300x400,300x450,250x250,3,3,675
2,300x300,300x400,300x450,250x250,3,3,675
3,300x300,300x350,300x450,250x250,3,3,675
4,300x300,300x320,300x450,250x250,3,3,675
...,...,...,...,...,...,...,...
316,350x420,350x470,350x600,250x400,5,9,3600
317,350x410,350x460,350x600,250x400,5,9,3600
318,350x400,350x440,350x600,250x400,5,9,3600
319,350x400,350x430,350x600,250x400,5,9,3600
320,350x400,350x420,350x600,250x400,5,9,3600

In [24]:
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x350,300x400,300x450,250x250,3,3,675
1,300x320,300x400,300x450,250x250,3,3,675
2,300x300,300x400,300x450,250x250,3,3,675
3,300x300,300x350,300x450,250x250,3,3,675
4,300x300,300x320,300x450,250x250,3,3,675
...,...,...,...,...,...,...,...
316,350x420,350x470,350x600,250x400,5,9,3600
317,350x410,350x460,350x600,250x400,5,9,3600
318,350x400,350x440,350x600,250x400,5,9,3600
319,350x400,350x430,350x600,250x400,5,9,3600
320,350x400,350x420,350x600,250x400,5,9,3600

In [25]:
dataset.isnull().sum()

Corner column(o/p)    0
Outer column(o/p)     0
Inner Column(o/p)     0
Beam(o/p)             0
Span(i/p)             0
Storey(i/p)           0
Area(sqm)(i/p)        0
dtype: int64

In [26]:
#Corner column
x=dataset.iloc[:,4:].values
y=dataset.iloc[:,:4].values
y

array([['300x350', '300x400', '300x450', '250x250'],
       ['300x320', '300x400', '300x450', '250x250'],
       ['300x300', '300x400', '300x450', '250x250'],
       ...,
       ['350x400', '350x440', '350x600', '250x400'],
       ['350x400', '350x430', '350x600', '250x400'],
       ['350x400', '350x420', '350x600', '250x400']], dtype=object)

In [27]:
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x350,300x400,300x450,250x250,3,3,675
1,300x320,300x400,300x450,250x250,3,3,675
2,300x300,300x400,300x450,250x250,3,3,675
3,300x300,300x350,300x450,250x250,3,3,675
4,300x300,300x320,300x450,250x250,3,3,675
...,...,...,...,...,...,...,...
316,350x420,350x470,350x600,250x400,5,9,3600
317,350x410,350x460,350x600,250x400,5,9,3600
318,350x400,350x440,350x600,250x400,5,9,3600
319,350x400,350x430,350x600,250x400,5,9,3600
320,350x400,350x420,350x600,250x400,5,9,3600

In [28]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame


# Split the column into separate integer columns
dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Outer column(o/p)', axis=1, inplace=True)

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\2925811356.py:18: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [29]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame


# Split the column into separate integer columns
dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Corner column(o/p)', axis=1, inplace=True)

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\2816941703.py:18: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [30]:
dataset

,Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width
0,300x450,250x250,3,3,675,300.0,400.0,300.0,350.0
1,300x450,250x250,3,3,675,300.0,400.0,300.0,320.0
2,300x450,250x250,3,3,675,300.0,400.0,300.0,300.0
3,300x450,250x250,3,3,675,300.0,350.0,300.0,300.0
4,300x450,250x250,3,3,675,300.0,320.0,300.0,300.0
...,...,...,...,...,...,...,...,...,...
316,350x600,250x400,5,9,3600,350.0,470.0,350.0,420.0
317,350x600,250x400,5,9,3600,350.0,460.0,350.0,410.0
318,350x600,250x400,5,9,3600,350.0,440.0,350.0,400.0
319,350x600,250x400,5,9,3600,350.0,430.0,350.0,400.0
320,350x600,250x400,5,9,3600,350.0,420.0,350.0,400.0

In [31]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values


# Split the column into separate integer columns
dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Inner Column(o/p)', axis=1, inplace=True)

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\794543552.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [32]:
dataset

,Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width
0,250x250,3,3,675,300.0,400.0,300.0,350.0,300.0,450.0
1,250x250,3,3,675,300.0,400.0,300.0,320.0,300.0,450.0
2,250x250,3,3,675,300.0,400.0,300.0,300.0,300.0,450.0
3,250x250,3,3,675,300.0,350.0,300.0,300.0,300.0,450.0
4,250x250,3,3,675,300.0,320.0,300.0,300.0,300.0,450.0
...,...,...,...,...,...,...,...,...,...,...
316,250x400,5,9,3600,350.0,470.0,350.0,420.0,350.0,600.0
317,250x400,5,9,3600,350.0,460.0,350.0,410.0,350.0,600.0
318,250x400,5,9,3600,350.0,440.0,350.0,400.0,350.0,600.0
319,250x400,5,9,3600,350.0,430.0,350.0,400.0,350.0,600.0
320,250x400,5,9,3600,350.0,420.0,350.0,400.0,350.0,600.0

In [33]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values


# Split the column into separate integer columns
dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Beam(o/p)', axis=1, inplace=True)

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\913776969.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

In [34]:
print(dataset.to_string())

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Outer height  Outer width  Corner height  Corner width  Inner height  Inner width  Beam height  Beam width
0            3            3             675         300.0        400.0          300.0         350.0         300.0        450.0        250.0       250.0
1            3            3             675         300.0        400.0          300.0         320.0         300.0        450.0        250.0       250.0
2            3            3             675         300.0        400.0          300.0         300.0         300.0        450.0        250.0       250.0
3            3            3             675         300.0        350.0          300.0         300.0         300.0        450.0        250.0       250.0
4            3            3             675         300.0        320.0          300.0         300.0         300.0        450.0        250.0       250.0
5            3            3             675         300.0        300.0          300.0         300.0         300.0        400.0        250.0       250.0
6            3            3             675         300.0        300.0          300.0         300.0         300.0        350.0        250.0       250.0
7            3            3             675         300.0        300.0          300.0         300.0         300.0        300.0        250.0       250.0
8            3            3             675         300.0        390.0          300.0         340.0         300.0        440.0        250.0       250.0
9            3            3             675         300.0        380.0          300.0         330.0         300.0        430.0        250.0       250.0
10           3            3             675         300.0        370.0          300.0         310.0         300.0        420.0        250.0       250.0
11           3            3             675         300.0        360.0          300.0         340.0         300.0        410.0        250.0       250.0
12           3            3             675         300.0        340.0          300.0         340.0         300.0        410.0        250.0       250.0
13           3            3             675         300.0        330.0          300.0         340.0         300.0        390.0        250.0       250.0
14           3            3             675         300.0        320.0          300.0         340.0         300.0        380.0        250.0       250.0
15           3            3             675         300.0        310.0          300.0         340.0         300.0        370.0        250.0       250.0
16           3            3             675         300.0        320.0          300.0         320.0         300.0        360.0        250.0       250.0
17           3            3             675         300.0        320.0          300.0         320.0         300.0        340.0        250.0       250.0
18           3            3             675         300.0        320.0          300.0         320.0         300.0        330.0        250.0       250.0
19           3            3             675         300.0        320.0          300.0         320.0         300.0        320.0        250.0       250.0
20           3            3             675         300.0        320.0          300.0         320.0         300.0        310.0        250.0       250.0
21           4            3             768         300.0        400.0          300.0         350.0         300.0        450.0        250.0       350.0
22           4            3             768         300.0        400.0          300.0         300.0         300.0        450.0        250.0       350.0
23           4            3             768         300.0        350.0          300.0         300.0         300.0        450.0        250.0       350.0
24           4            3             768         300.0        320.0          300.0         300.0         300.0        450.0        250.0       350.0
25           4            3             768         300.0        390.0          300.0         340.0         300.0        440.0        250.0       250.0
26           4            3             768         300.0        380.0          300.0         330.0         300.0        430.0        250.0       250.0
27           4            3             768         300.0        370.0          300.0         320.0         300.0        420.0        250.0       250.0
28           4            3             768         300.0        360.0          300.0         310.0         300.0        410.0        250.0       250.0
29           4            3             768         300.0        340.0          300.0         320.0         300.0        400.0        250.0       250.0
30           4            3             768         300.0        330.0          300.0         320.0         300.0        390.0        250.0       250.0
31           4            3             768         300.0        320.0          300.0         320.0         300.0        380.0        250.0       250.0
32           4            3             768         300.0        320.0          300.0         320.0         300.0        370.0        250.0       250.0
33           4            3             768         300.0        320.0          300.0         320.0         300.0        360.0        250.0       250.0
34           4            3             768         300.0        320.0          300.0         320.0         300.0        350.0        250.0       250.0
35           4            3             768         300.0        320.0          300.0         320.0         300.0        340.0        250.0       250.0
36           4            3             768         300.0        320.0          300.0         320.0         300.0        330.0        250.0       250.0
37           4            3             768         300.0        320.0          300.0         320.0         300.0        320.0        250.0       250.0
38           4            3             768         300.0        320.0          300.0         320.0         300.0        310.0        250.0       250.0
39           5            3            1200         350.0        450.0          350.0         350.0         350.0        500.0        250.0       450.0
40           5            3            1200         350.0        450.0          350.0         300.0         350.0        500.0        250.0       450.0
41           5            3            1200         350.0        400.0          350.0         300.0         350.0        500.0        250.0       450.0
42           5            3            1200         350.0        400.0          350.0         300.0         350.0        450.0        250.0       450.0
43           5            3            1200         350.0        400.0          350.0         300.0         350.0        400.0        250.0       450.0
44           5            3            1200         350.0        440.0          350.0         340.0         350.0        490.0        250.0       450.0
45           5            3            1200         350.0        430.0          350.0         330.0         350.0        480.0        250.0       450.0
46           5            3            1200         350.0        420.0          350.0         320.0         350.0        470.0        250.0       450.0
47           5            3            1200         350.0        410.0          350.0         310.0         350.0        460.0        250.0       450.0
48           5            3            1200         350.0        410.0          350.0         310.0         350.0        440.0        250.0       450.0
49           5            3            1200         350.0        410.0          350.0         320.0         350.0        430.0        250.0       450.0
50           5            3            1200         350.0        410.0          350.0         320.0         350.0        420.0        250.0       450.0
51           5            3            1200         350.0        420.0          350.0         310.0         350.0        410.0        250.0       450.0
52           3            5            1125         350.0        500.0          350.0         450.0         350.0        550.0        250.0       250.0
53           3            5            1125         350.0        400.0          350.0         350.0         350.0        400.0        250.0       250.0
54           3            5            1125         350.0        490.0          350.0         440.0         350.0        540.0        250.0       250.0
55           3            5            1125         350.0        480.0          350.0         430.0         350.0        530.0        250.0       250.0
56           3            5            1125         350.0        470.0          350.0         420.0         350.0        520.0        250.0       250.0
57           3            5            1125         350.0        460.0          350.0         410.0         350.0        510.0        250.0       250.0
58           3            5            1125         350.0        450.0          350.0         400.0         350.0        500.0        250.0       250.0
59           3            5            1125         350.0        440.0          350.0         390.0         350.0        490.0        250.0       250.0
60           3            5            1125         350.0        430.0          350.0         380.0         350.0        480.0        250.0       250.0
61           3            5            1125         350.0        420.0          350.0         370.0         350.0        470.0        250.0       250.0
62           3            5            1125         350.0        410.0          350.0         360.0         350.0        460.0        250.0       250.0
63           3            5            1125         350.0        400.0          350.0         350.0         350.0        450.0        250.0       250.0
64           3            5            1125         350.0        390.0          350.0         360.0         350.0        440.0        250.0       250.0
65           3            5            1125         350.0        410.0          350.0         370.0         350.0        430.0        250.0       250.0
66           3            5            1125         350.0        390.0          350.0         350.0         350.0        420.0        250.0       250.0
67           3            5            1125         350.0        400.0          350.0         360.0         350.0        410.0        250.0       250.0
68           3            6            1350         350.0        500.0          350.0         450.0         350.0        550.0        250.0       250.0
69           3            6            1350         350.0        500.0          350.0         400.0         350.0        550.0        250.0       250.0
70           3            6            1350         350.0        500.0          350.0         350.0         350.0        550.0        250.0       250.0
71           3            6            1350         350.0        450.0          350.0         350.0         350.0        550.0        250.0       250.0
72           3            6            1350         350.0        400.0          350.0         350.0         350.0        550.0        250.0       250.0
73           3            6            1350         350.0        410.0          350.0         360.0         350.0        550.0        250.0       250.0
74           3            6            1350         350.0        420.0          350.0         370.0         350.0        550.0        250.0       250.0
75           3            6            1350         350.0        430.0          300.0         380.0         350.0        550.0        250.0       250.0
76           3            6            1350         300.0        440.0          300.0         390.0         350.0        550.0        250.0       250.0
77           3            6            1350         300.0        460.0          300.0         410.0         350.0        550.0        250.0       250.0
78           3            6            1350         300.0        470.0          300.0         420.0         350.0        550.0        250.0       250.0
79           3            6            1350         300.0        380.0          300.0         430.0         350.0        550.0        250.0       250.0
80           3            6            1350         300.0        390.0          300.0         440.0         350.0        550.0        250.0       250.0
81           4            6            1536           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
82           4            6            1536           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
83           4            6            1536           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
84           4            6            1536           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
85           4            6            1536           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
86           4            6            1536           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
88           4            6            1536         350.0        490.0          350.0         440.0         350.0        540.0        250.0       350.0
89           4            6            1536         350.0        480.0          350.0         430.0         350.0        530.0        250.0       350.0
90           4            6            1536         350.0        470.0          350.0         420.0         350.0        520.0        250.0       350.0
91           4            6            1536         350.0        460.0          350.0         410.0         350.0        510.0        250.0       350.0
92           4            6            1536         350.0        440.0          350.0         390.0         350.0        510.0        250.0       350.0
93           4            6            1536         350.0        430.0          350.0         380.0         350.0        510.0        250.0       350.0
94           4            6            1536         350.0        420.0          350.0         370.0         350.0        510.0        250.0       350.0
95           4            6            1536         350.0        410.0          350.0         360.0         350.0        510.0        250.0       350.0
96           5            6            2400           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
97           5            6            2400           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
98           5            6            2400           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
99           5            6            2400           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
100          5            6            2400           NaN          NaN            NaN           NaN           NaN          NaN          NaN         NaN
102          5            6            2400         350.0        490.0          350.0         440.0         350.0        550.0        250.0       450.0
103          5            6            2400         350.0        480.0          350.0         430.0         350.0        550.0        250.0       450.0
104          5            6            2400         350.0        470.0          350.0         420.0         350.0        550.0        250.0       450.0
105          5            6            2400         350.0        460.0          350.0         410.0         350.0        550.0        250.0       450.0
106          5            6            2400         350.0        440.0          350.0         390.0         350.0        550.0        250.0       450.0
107          5            6            2400         350.0        430.0          350.0         380.0         350.0        550.0        250.0       450.0
108          5            6            2400         350.0        420.0          350.0         370.0         350.0        550.0        250.0       450.0
109          5            6            2400         350.0        410.0          350.0         360.0         350.0        550.0        250.0       450.0
110          3            7            1575         300.0        600.0          300.0         550.0         600.0        650.0        250.0       300.0
111          3            7            1575         300.0        350.0          300.0         350.0         300.0        400.0        250.0       300.0
112          3            7            1575         300.0        590.0          300.0         540.0         300.0        640.0        250.0       300.0
113          3            7            1575         300.0        580.0          300.0         530.0         300.0        630.0        250.0       300.0
114          3            7            1575         300.0        570.0          300.0         520.0         300.0        620.0        250.0       300.0
115          3            7            1575         300.0        560.0          300.0         510.0         300.0        610.0        250.0       300.0
116          3            7            1575         300.0        550.0          300.0         500.0         300.0        600.0        250.0       300.0
117          3            7            1575         300.0        540.0          300.0         490.0         300.0        590.0        250.0       300.0
118          3            7            1575         300.0        530.0          300.0         480.0         300.0        580.0        250.0       300.0
119          3            7            1575         300.0        520.0          300.0         470.0         300.0        570.0        250.0       300.0
120          3            7            1575         300.0        510.0          300.0         460.0         300.0        560.0        250.0       300.0
121          3            7            1575         300.0        500.0          300.0         450.0         300.0        550.0        250.0       300.0
122          3            7            1575         300.0        490.0          300.0         440.0         300.0        540.0        250.0       300.0
123          3            7            1575         300.0        480.0          300.0         430.0         300.0        530.0        250.0       300.0
124          3            7            1575         300.0        470.0          300.0         420.0         300.0        520.0        250.0       300.0
125          3            7            1575         300.0        460.0          300.0         410.0         300.0        510.0        250.0       300.0
126          3            7            1575         300.0        450.0          300.0         400.0         300.0        500.0        250.0       300.0
127          3            7            1575         300.0        440.0          300.0         390.0         300.0        490.0        250.0       300.0
128          3            7            1575         300.0        430.0          300.0         380.0         300.0        480.0        250.0       300.0
129          3            7            1575         300.0        420.0          300.0         370.0         300.0        470.0        250.0       300.0
130          3            7            1575         300.0        410.0          300.0         360.0         300.0        460.0        250.0       300.0
131          3            7            1575         300.0        400.0          300.0         350.0         300.0        450.0        250.0       300.0

In [35]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
0,3,3,675,300.0,400.0,300.0,350.0,300.0,450.0,250.0,250.0
1,3,3,675,300.0,400.0,300.0,320.0,300.0,450.0,250.0,250.0
2,3,3,675,300.0,400.0,300.0,300.0,300.0,450.0,250.0,250.0
3,3,3,675,300.0,350.0,300.0,300.0,300.0,450.0,250.0,250.0
4,3,3,675,300.0,320.0,300.0,300.0,300.0,450.0,250.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...
316,5,9,3600,350.0,470.0,350.0,420.0,350.0,600.0,250.0,400.0
317,5,9,3600,350.0,460.0,350.0,410.0,350.0,600.0,250.0,400.0
318,5,9,3600,350.0,440.0,350.0,400.0,350.0,600.0,250.0,400.0
319,5,9,3600,350.0,430.0,350.0,400.0,350.0,600.0,250.0,400.0
320,5,9,3600,350.0,420.0,350.0,400.0,350.0,600.0,250.0,400.0

In [36]:
dataset.isnull().sum()

Span(i/p)          0
Storey(i/p)        0
Area(sqm)(i/p)     0
Outer height      56
Outer width       56
Corner height     32
Corner width      32
Inner height      32
Inner width       32
Beam height       63
Beam width        63
dtype: int64

In [37]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
0,3,3,675,300.0,400.0,300.0,350.0,300.0,450.0,250.0,250.0
1,3,3,675,300.0,400.0,300.0,320.0,300.0,450.0,250.0,250.0
2,3,3,675,300.0,400.0,300.0,300.0,300.0,450.0,250.0,250.0
3,3,3,675,300.0,350.0,300.0,300.0,300.0,450.0,250.0,250.0
4,3,3,675,300.0,320.0,300.0,300.0,300.0,450.0,250.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...
316,5,9,3600,350.0,470.0,350.0,420.0,350.0,600.0,250.0,400.0
317,5,9,3600,350.0,460.0,350.0,410.0,350.0,600.0,250.0,400.0
318,5,9,3600,350.0,440.0,350.0,400.0,350.0,600.0,250.0,400.0
319,5,9,3600,350.0,430.0,350.0,400.0,350.0,600.0,250.0,400.0
320,5,9,3600,350.0,420.0,350.0,400.0,350.0,600.0,250.0,400.0

In [38]:
#Corner column
x=dataset.iloc[:,:3].values
y=dataset.iloc[:,3:].values

In [39]:
# Splitting the dataset into training and test set. 


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [40]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
0,3,3,675,300.0,400.0,300.0,350.0,300.0,450.0,250.0,250.0
1,3,3,675,300.0,400.0,300.0,320.0,300.0,450.0,250.0,250.0
2,3,3,675,300.0,400.0,300.0,300.0,300.0,450.0,250.0,250.0
3,3,3,675,300.0,350.0,300.0,300.0,300.0,450.0,250.0,250.0
4,3,3,675,300.0,320.0,300.0,300.0,300.0,450.0,250.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...
316,5,9,3600,350.0,470.0,350.0,420.0,350.0,600.0,250.0,400.0
317,5,9,3600,350.0,460.0,350.0,410.0,350.0,600.0,250.0,400.0
318,5,9,3600,350.0,440.0,350.0,400.0,350.0,600.0,250.0,400.0
319,5,9,3600,350.0,430.0,350.0,400.0,350.0,600.0,250.0,400.0
320,5,9,3600,350.0,420.0,350.0,400.0,350.0,600.0,250.0,400.0

In [41]:
#dropping duplicate values
dataset.drop_duplicates(inplace=True)
print(dataset.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
316    False
317    False
318    False
319    False
320    False
Length: 291, dtype: bool

In [42]:
# Split the dataset into input features and target variables
X = dataset[['Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)']]
y = dataset[['Inner height', 'Inner width', 'Outer height', 'Outer width', 'Corner height', 'Corner width', 'Beam height', 'Beam width']]

In [43]:
y

,Inner height,Inner width,Outer height,Outer width,Corner height,Corner width,Beam height,Beam width
0,300.0,450.0,300.0,400.0,300.0,350.0,250.0,250.0
1,300.0,450.0,300.0,400.0,300.0,320.0,250.0,250.0
2,300.0,450.0,300.0,400.0,300.0,300.0,250.0,250.0
3,300.0,450.0,300.0,350.0,300.0,300.0,250.0,250.0
4,300.0,450.0,300.0,320.0,300.0,300.0,250.0,250.0
...,...,...,...,...,...,...,...,...
316,350.0,600.0,350.0,470.0,350.0,420.0,250.0,400.0
317,350.0,600.0,350.0,460.0,350.0,410.0,250.0,400.0
318,350.0,600.0,350.0,440.0,350.0,400.0,250.0,400.0
319,350.0,600.0,350.0,430.0,350.0,400.0,250.0,400.0
320,350.0,600.0,350.0,420.0,350.0,400.0,250.0,400.0

In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

dataset.fillna(0, inplace=True)

# Split the dataset into input features and target variables
X = dataset[['Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)']]
y = dataset[['Inner height', 'Inner width', 'Outer height', 'Outer width', 'Corner height', 'Corner width', 'Beam height', 'Beam width']]

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the mean squared error (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Predict dimensions for new data
new_data = {
    'Span(i/p)': [3],
    'Storey(i/p)': [4],
    'Area(sqm)(i/p)': [864],
}
new_df = pd.DataFrame(new_data)

predicted_dimensions = model.predict(new_df)
inner_dim = predicted_dimensions[0][:2].astype(int)
outer_dim = predicted_dimensions[0][2:4].astype(int)
corner_dim = predicted_dimensions[0][4:6].astype(int)
beam_dim = predicted_dimensions[0][6:].astype(int)

print("Square shape:-")
print(f"Inner Dimension: {max(inner_dim[0], 250)}x{max(inner_dim[1], 250)}")
print(f"Outer Dimension: {max(outer_dim[0], 250)}x{max(outer_dim[1], 250)}")
print(f"Corner Dimension: {max(corner_dim[0], 250)}x{max(corner_dim[1], 250)}")
print(f"Beam Dimension: {max(beam_dim[0], 250)}x{max(beam_dim[1], 250)}")

Mean Squared Error: 8356.808956920635
Square shape:-
Inner Dimension: 307x412
Outer Dimension: 352x454
Corner Dimension: 301x332
Beam Dimension: 275x291

In [751]:
#We can also check the score for training dataset and test dataset


#print("train score : " , model.score(X_train,y_train))
#print("test score : " , model.score(X_test,y_test))

# L SHAPE

In [2]:
#Importing dataset : 
dataset=pd.read_csv("L.csv")
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,350X600,350X650,350X700,250X300,3,9,1296
1,350X550,350X650,350X700,250X300,3,9,1296
2,350X500,350X650,350X700,250X300,3,9,1296
3,350X450,350X650,350X700,250X300,3,9,1296
4,350X400,350X650,350X700,250X300,3,9,1296
...,...,...,...,...,...,...,...
1203,350X400,350X440,350X500,250X450,5,2,600
1204,350X400,350X430,350X500,250X450,5,2,600
1205,350X390,350X440,350X500,250X450,5,2,600
1206,350X380,350X430,350X500,250X450,5,2,600
1207,350X380,350X420,350X500,250X450,5,2,600

In [3]:
#  FINDING NULL VALUES IN THE DATASET
print ( "NULL VALUES : \n" , dataset . isnull())

NULL VALUES :
       Corner column(o/p)  Outer column(o/p)  Inner Column(o/p)  Beam(o/p)  \
0                  False              False              False      False
1                  False              False              False      False
2                  False              False              False      False
3                  False              False              False      False
4                  False              False              False      False
...                  ...                ...                ...        ...
1203               False              False              False      False
1204               False              False              False      False
1205               False              False              False      False
1206               False              False              False      False
1207               False              False              False      False

      Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
0         False        False           False
1         False        False           False
2         False        False           False
3         False        False           False
4         False        False           False
...         ...          ...             ...
1203      False        False           False
1204      False        False           False
1205      False        False           False
1206      False        False           False
1207      False        False           False

[1208 rows x 7 columns]

In [4]:
#checking duplicate values
print(dataset.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
1203     True
1204     True
1205     True
1206     True
1207     True
Length: 1208, dtype: bool

In [5]:
#dropping duplicate values
dataset.drop_duplicates(inplace=True)
print(dataset.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
297    False
298    False
299    False
300    False
301    False
Length: 300, dtype: bool

In [6]:
#Corner column
x=dataset.iloc[:,4:].values
y=dataset.iloc[:,0].values

In [7]:
dataset.isnull().sum()

Corner column(o/p)    0
Outer column(o/p)     0
Inner Column(o/p)     0
Beam(o/p)             0
Span(i/p)             0
Storey(i/p)           0
Area(sqm)(i/p)        0
dtype: int64

In [8]:
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,350X600,350X650,350X700,250X300,3,9,1296
1,350X550,350X650,350X700,250X300,3,9,1296
2,350X500,350X650,350X700,250X300,3,9,1296
3,350X450,350X650,350X700,250X300,3,9,1296
4,350X400,350X650,350X700,250X300,3,9,1296
...,...,...,...,...,...,...,...
297,350X400,350X440,350X500,250X450,5,2,600
298,350X400,350X430,350X500,250X450,5,2,600
299,350X390,350X440,350X500,250X450,5,2,600
300,350X380,350X430,350X500,250X450,5,2,600
301,350X380,350X420,350X500,250X450,5,2,600

In [9]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Outer column(o/p)', axis=1, inplace=True)

print(dataset)

    Corner column(o/p) Inner Column(o/p) Beam(o/p)  Span(i/p)  Storey(i/p)  \
0              350X600           350X700   250X300          3            9
1              350X550           350X700   250X300          3            9
2              350X500           350X700   250X300          3            9
3              350X450           350X700   250X300          3            9
4              350X400           350X700   250X300          3            9
..                 ...               ...       ...        ...          ...
297            350X400           350X500   250X450          5            2
298            350X400           350X500   250X450          5            2
299            350X390           350X500   250X450          5            2
300            350X380           350X500   250X450          5            2
301            350X380           350X500   250X450          5            2

     Area(sqm)(i/p)  Outer height  Outer width
0              1296         350.0        650.0
1              1296         350.0        650.0
2              1296         350.0        650.0
3              1296         350.0        650.0
4              1296         350.0        650.0
..              ...           ...          ...
297             600         350.0        440.0
298             600         350.0        430.0
299             600         350.0        440.0
300             600         350.0        430.0
301             600         350.0        420.0

[300 rows x 8 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_5240\3711316056.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [10]:
dataset

,Corner column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width
0,350X600,350X700,250X300,3,9,1296,350.0,650.0
1,350X550,350X700,250X300,3,9,1296,350.0,650.0
2,350X500,350X700,250X300,3,9,1296,350.0,650.0
3,350X450,350X700,250X300,3,9,1296,350.0,650.0
4,350X400,350X700,250X300,3,9,1296,350.0,650.0
...,...,...,...,...,...,...,...,...
297,350X400,350X500,250X450,5,2,600,350.0,440.0
298,350X400,350X500,250X450,5,2,600,350.0,430.0
299,350X390,350X500,250X450,5,2,600,350.0,440.0
300,350X380,350X500,250X450,5,2,600,350.0,430.0
301,350X380,350X500,250X450,5,2,600,350.0,420.0

In [11]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Corner column(o/p)', axis=1, inplace=True)

print(dataset)

    Inner Column(o/p) Beam(o/p)  Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  \
0             350X700   250X300          3            9            1296
1             350X700   250X300          3            9            1296
2             350X700   250X300          3            9            1296
3             350X700   250X300          3            9            1296
4             350X700   250X300          3            9            1296
..                ...       ...        ...          ...             ...
297           350X500   250X450          5            2             600
298           350X500   250X450          5            2             600
299           350X500   250X450          5            2             600
300           350X500   250X450          5            2             600
301           350X500   250X450          5            2             600

     Outer height  Outer width  Corner height  Corner width
0           350.0        650.0          350.0         600.0
1           350.0        650.0          350.0         550.0
2           350.0        650.0          350.0         500.0
3           350.0        650.0          350.0         450.0
4           350.0        650.0          350.0         400.0
..            ...          ...            ...           ...
297         350.0        440.0          350.0         400.0
298         350.0        430.0          350.0         400.0
299         350.0        440.0          350.0         390.0
300         350.0        430.0          350.0         380.0
301         350.0        420.0          350.0         380.0

[300 rows x 9 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_5240\519432503.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [12]:
dataset

,Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width
0,350X700,250X300,3,9,1296,350.0,650.0,350.0,600.0
1,350X700,250X300,3,9,1296,350.0,650.0,350.0,550.0
2,350X700,250X300,3,9,1296,350.0,650.0,350.0,500.0
3,350X700,250X300,3,9,1296,350.0,650.0,350.0,450.0
4,350X700,250X300,3,9,1296,350.0,650.0,350.0,400.0
...,...,...,...,...,...,...,...,...,...
297,350X500,250X450,5,2,600,350.0,440.0,350.0,400.0
298,350X500,250X450,5,2,600,350.0,430.0,350.0,400.0
299,350X500,250X450,5,2,600,350.0,440.0,350.0,390.0
300,350X500,250X450,5,2,600,350.0,430.0,350.0,380.0
301,350X500,250X450,5,2,600,350.0,420.0,350.0,380.0

In [13]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Inner Column(o/p)', axis=1, inplace=True)

print(dataset)

    Beam(o/p)  Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Outer height  \
0     250X300          3            9            1296         350.0
1     250X300          3            9            1296         350.0
2     250X300          3            9            1296         350.0
3     250X300          3            9            1296         350.0
4     250X300          3            9            1296         350.0
..        ...        ...          ...             ...           ...
297   250X450          5            2             600         350.0
298   250X450          5            2             600         350.0
299   250X450          5            2             600         350.0
300   250X450          5            2             600         350.0
301   250X450          5            2             600         350.0

     Outer width  Corner height  Corner width  Inner height  Inner width
0          650.0          350.0         600.0         350.0        700.0
1          650.0          350.0         550.0         350.0        700.0
2          650.0          350.0         500.0         350.0        700.0
3          650.0          350.0         450.0         350.0        700.0
4          650.0          350.0         400.0         350.0        700.0
..           ...            ...           ...           ...          ...
297        440.0          350.0         400.0         350.0        500.0
298        430.0          350.0         400.0         350.0        500.0
299        440.0          350.0         390.0         350.0        500.0
300        430.0          350.0         380.0         350.0        500.0
301        420.0          350.0         380.0         350.0        500.0

[300 rows x 10 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_5240\4116055036.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [14]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Beam(o/p)', axis=1, inplace=True)

print(dataset)

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Outer height  Outer width  \
0            3            9            1296         350.0        650.0
1            3            9            1296         350.0        650.0
2            3            9            1296         350.0        650.0
3            3            9            1296         350.0        650.0
4            3            9            1296         350.0        650.0
..         ...          ...             ...           ...          ...
297          5            2             600         350.0        440.0
298          5            2             600         350.0        430.0
299          5            2             600         350.0        440.0
300          5            2             600         350.0        430.0
301          5            2             600         350.0        420.0

     Corner height  Corner width  Inner height  Inner width  Beam height  \
0            350.0         600.0         350.0        700.0        250.0
1            350.0         550.0         350.0        700.0        250.0
2            350.0         500.0         350.0        700.0        250.0
3            350.0         450.0         350.0        700.0        250.0
4            350.0         400.0         350.0        700.0        250.0
..             ...           ...           ...          ...          ...
297          350.0         400.0         350.0        500.0        250.0
298          350.0         400.0         350.0        500.0        250.0
299          350.0         390.0         350.0        500.0        250.0
300          350.0         380.0         350.0        500.0        250.0
301          350.0         380.0         350.0        500.0        250.0

     Beam width
0         300.0
1         300.0
2         300.0
3         300.0
4         300.0
..          ...
297       450.0
298       450.0
299       450.0
300       450.0
301       450.0

[300 rows x 11 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_5240\2830076836.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

In [15]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
0,3,9,1296,350.0,650.0,350.0,600.0,350.0,700.0,250.0,300.0
1,3,9,1296,350.0,650.0,350.0,550.0,350.0,700.0,250.0,300.0
2,3,9,1296,350.0,650.0,350.0,500.0,350.0,700.0,250.0,300.0
3,3,9,1296,350.0,650.0,350.0,450.0,350.0,700.0,250.0,300.0
4,3,9,1296,350.0,650.0,350.0,400.0,350.0,700.0,250.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...
297,5,2,600,350.0,440.0,350.0,400.0,350.0,500.0,250.0,450.0
298,5,2,600,350.0,430.0,350.0,400.0,350.0,500.0,250.0,450.0
299,5,2,600,350.0,440.0,350.0,390.0,350.0,500.0,250.0,450.0
300,5,2,600,350.0,430.0,350.0,380.0,350.0,500.0,250.0,450.0
301,5,2,600,350.0,420.0,350.0,380.0,350.0,500.0,250.0,450.0

In [16]:
dataset.isnull().sum()

Span(i/p)          0
Storey(i/p)        0
Area(sqm)(i/p)     0
Outer height      83
Outer width       83
Corner height     82
Corner width      82
Inner height      81
Inner width       81
Beam height       91
Beam width        91
dtype: int64

In [17]:
dataset.dropna(inplace=True)

In [18]:
print(dataset.to_string())

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Outer height  Outer width  Corner height  Corner width  Inner height  Inner width  Beam height  Beam width
0            3            9            1296         350.0        650.0          350.0         600.0         350.0        700.0        250.0       300.0
1            3            9            1296         350.0        650.0          350.0         550.0         350.0        700.0        250.0       300.0
2            3            9            1296         350.0        650.0          350.0         500.0         350.0        700.0        250.0       300.0
3            3            9            1296         350.0        650.0          350.0         450.0         350.0        700.0        250.0       300.0
4            3            9            1296         350.0        650.0          350.0         400.0         350.0        700.0        250.0       300.0
5            3            9            1296         350.0        600.0          350.0         400.0         350.0        700.0        250.0       300.0
26           3            8            1152         350.0        600.0          350.0         400.0         350.0        700.0        250.0       300.0
27           3            8            1152         350.0        590.0          350.0         400.0         350.0        690.0        250.0       300.0
28           3            8            1152         350.0        580.0          350.0         400.0         350.0        680.0        250.0       300.0
29           3            8            1152         350.0        570.0          350.0         400.0         350.0        670.0        250.0       300.0
30           3            8            1152         350.0        560.0          350.0         400.0         350.0        660.0        250.0       300.0
31           3            8            1152         350.0        550.0          350.0         400.0         350.0        650.0        250.0       300.0
32           3            8            1152         350.0        540.0          350.0         400.0         350.0        640.0        250.0       300.0
33           3            8            1152         350.0        530.0          350.0         400.0         350.0        630.0        250.0       300.0
34           3            8            1152         350.0        520.0          350.0         400.0         350.0        620.0        250.0       300.0
35           3            8            1152         350.0        510.0          350.0         400.0         350.0        610.0        250.0       300.0
36           3            8            1152         350.0        500.0          350.0         400.0         350.0        600.0        250.0       300.0
37           3            8            1152         350.0        490.0          350.0         390.0         350.0        590.0        250.0       300.0
38           3            8            1152         350.0        480.0          350.0         380.0         350.0        580.0        250.0       300.0
39           3            8            1152         350.0        470.0          350.0         370.0         350.0        570.0        250.0       300.0
40           3            8            1152         350.0        460.0          350.0         360.0         350.0        560.0        250.0       300.0
41           3            8            1152         350.0        450.0          350.0         350.0         350.0        550.0        250.0       300.0
42           3            8            1152         350.0        440.0          350.0         350.0         350.0        540.0        250.0       300.0
43           3            8            1152         350.0        430.0          350.0         350.0         350.0        530.0        250.0       300.0
44           3            8            1152         350.0        420.0          350.0         350.0         350.0        520.0        250.0       300.0
45           3            8            1152         350.0        410.0          350.0         350.0         350.0        510.0        250.0       300.0
46           3            8            1152         350.0        400.0          350.0         350.0         350.0        500.0        250.0       300.0
47           3            8            1152         350.0        400.0          350.0         350.0         350.0        490.0        250.0       300.0
48           3            8            1152         350.0        400.0          350.0         350.0         350.0        480.0        250.0       300.0
49           3            8            1152         350.0        400.0          350.0         350.0         350.0        470.0        250.0       300.0
50           3            8            1152         350.0        400.0          350.0         350.0         350.0        460.0        250.0       300.0
51           3            8            1152         350.0        400.0          350.0         350.0         350.0        450.0        250.0       300.0
52           3            8            1152         350.0        400.0          350.0         350.0         350.0        440.0        250.0       300.0
53           3            8            1152         350.0        400.0          350.0         350.0         350.0        430.0        250.0       300.0
54           3            6             864         350.0        600.0          350.0         450.0         350.0        450.0        250.0       300.0
55           3            6             864         300.0        400.0          300.0         350.0         300.0        450.0        250.0       300.0
56           3            6             864         300.0        350.0          300.0         300.0         300.0        450.0        250.0       300.0
57           3            6             864         300.0        350.0          300.0         300.0         300.0        400.0        250.0       300.0
58           3            6             864         300.0        350.0          300.0         300.0         300.0        350.0        250.0       300.0
68           3            5             720         350.0        500.0          350.0         450.0         350.0        550.0        250.0       300.0
69           3            5             720         350.0        490.0          350.0         440.0         350.0        540.0        250.0       300.0
70           3            5             720         350.0        480.0          350.0         430.0         350.0        530.0        250.0       300.0
71           3            5             720         350.0        470.0          350.0         420.0         350.0        520.0        250.0       300.0
72           3            5             720         350.0        460.0          350.0         410.0         350.0        510.0        250.0       300.0
73           3            5             720         350.0        450.0          350.0         400.0         350.0        500.0        250.0       300.0
74           3            5             720         350.0        440.0          350.0         390.0         350.0        490.0        250.0       300.0
75           3            5             720         350.0        430.0          350.0         380.0         350.0        480.0        250.0       300.0
76           3            5             720         350.0        420.0          350.0         370.0         350.0        470.0        250.0       300.0
77           3            5             720         350.0        410.0          350.0         360.0         350.0        460.0        250.0       300.0
78           3            5             720         350.0        400.0          350.0         350.0         350.0        450.0        250.0       300.0
79           3            5             720         300.0        500.0          300.0         450.0         300.0        550.0        250.0       300.0
80           3            5             720         300.0        490.0          300.0         440.0         300.0        540.0        250.0       300.0
81           3            5             720         300.0        480.0          300.0         430.0         300.0        530.0        250.0       300.0
82           3            5             720         300.0        470.0          300.0         420.0         300.0        520.0        250.0       300.0
83           3            5             720         300.0        460.0          300.0         410.0         300.0        510.0        250.0       300.0
84           3            5             720         300.0        450.0          300.0         400.0         300.0        400.0        250.0       300.0
85           3            5             720         300.0        440.0          300.0         390.0         300.0        490.0        250.0       300.0
86           3            5             720         300.0        430.0          300.0         380.0         300.0        480.0        250.0       300.0
87           3            5             720         300.0        420.0          300.0         370.0         300.0        470.0        250.0       300.0
88           3            5             720         300.0        410.0          300.0         360.0         300.0        460.0        250.0       300.0
89           3            5             720         300.0        400.0          300.0         350.0         300.0        450.0        250.0       300.0
90           3            5             720         300.0        390.0          300.0         340.0         300.0        440.0        250.0       300.0
91           3            5             720         300.0        380.0          300.0         330.0         300.0        430.0        250.0       300.0
92           3            5             720         300.0        370.0          300.0         320.0         300.0        420.0        250.0       300.0
93           3            5             720         300.0        360.0          300.0         310.0         300.0        410.0        250.0       300.0
94           3            5             720         300.0        350.0          300.0         300.0         300.0        400.0        250.0       300.0
95           3            5             720         300.0        340.0          300.0         300.0         300.0        390.0        250.0       300.0
96           3            5             720         300.0        330.0          300.0         300.0         300.0        380.0        250.0       300.0
97           3            5             720         300.0        320.0          300.0         300.0         300.0        370.0        250.0       300.0
98           3            5             720         300.0        310.0          300.0         300.0         300.0        360.0        250.0       300.0
99           3            5             720         300.0        300.0          300.0         300.0         300.0        350.0        250.0       300.0
100          3            5             720         300.0        300.0          300.0         300.0         300.0        340.0        250.0       300.0
101          3            5             720         300.0        300.0          300.0         300.0         300.0        330.0        250.0       300.0
102          3            5             720         300.0        300.0          300.0         300.0         300.0        320.0        250.0       300.0
103          3            5             720         300.0        300.0          300.0         300.0         300.0        310.0        250.0       300.0
104          3            5             720         300.0        300.0          300.0         300.0         300.0        300.0        250.0       300.0
111          3            3             432         300.0        300.0          300.0         300.0         300.0        350.0        250.0       250.0
131          3            2             288         300.0        360.0          300.0         310.0         300.0        410.0        250.0       250.0
136          3            2             288         300.0        310.0          300.0         300.0         300.0        360.0        250.0       250.0
137          3            2             288         300.0        300.0          300.0         300.0         300.0        350.0        250.0       250.0
142          3            2             288         300.0        300.0          300.0         300.0         300.0        300.0        250.0       250.0
143          4            9            1728         300.0        650.0          300.0         600.0         300.0        700.0        250.0       400.0
144          4            9            1728         300.0        650.0          300.0         550.0         300.0        720.0        250.0       400.0
145          4            9            1728         350.0        600.0          350.0         550.0         350.0        650.0        250.0       400.0
146          4            9            1728         350.0        600.0          350.0         500.0         350.0        650.0        250.0       400.0
147          4            9            1728         350.0        600.0          350.0         450.0         350.0        650.0        250.0       400.0
148          4            9            1728         350.0        600.0          350.0         400.0         350.0        650.0        250.0       400.0
149          4            9            1728         350.0        550.0          350.0         400.0         350.0        650.0        250.0       400.0
164          4            8            1536         300.0        650.0          300.0         600.0         300.0        700.0        250.0       400.0
165          4            8            1536         300.0        640.0          300.0         590.0         300.0        690.0        250.0       400.0
166          4            8            1536         300.0        630.0          300.0         580.0         300.0        680.0        250.0       400.0
167          4            8            1536         300.0        620.0          300.0         570.0         300.0        670.0        250.0       400.0
168          4            8            1536         300.0        610.0          300.0         560.0         300.0        660.0        250.0       400.0
169          4            8            1536         300.0        600.0          300.0         550.0         300.0        650.0        250.0       400.0
170          4            8            1536         300.0        600.0          300.0         540.0         300.0        640.0        250.0       400.0
171          4            8            1536         300.0        600.0          300.0         530.0         300.0        630.0        250.0       400.0
172          4            8            1536         300.0        600.0          300.0         520.0         300.0        620.0        250.0       400.0
173          4            8            1536         300.0        600.0          300.0         510.0         300.0        620.0        250.0       400.0
174          4            8            1536         300.0        600.0          300.0         500.0         300.0        620.0        250.0       400.0
175          4            8            1536         350.0        550.0          350.0         400.0         350.0        650.0        250.0       400.0
176          4            8            1536         350.0        540.0          350.0         400.0         350.0        640.0        250.0       400.0
177          4            8            1536         350.0        550.0          350.0         400.0         350.0        630.0        250.0       400.0
178          4            8            1536         350.0        540.0          350.0         400.0         350.0        620.0        250.0       400.0
179          4            8            1536         350.0        530.0          350.0         400.0         350.0        610.0        250.0       400.0
180          4            8            1536         350.0        520.0          350.0         400.0         350.0        600.0        250.0       400.0
181          4            8            1536         350.0        510.0          350.0         400.0         350.0        590.0        250.0       400.0
182          4            8            1536         350.0        500.0          350.0         400.0         350.0        580.0        250.0       400.0
183          4            8            1536         350.0        490.0          350.0         400.0         350.0        570.0        250.0       400.0
184          4            8            1536         350.0        480.0          350.0         400.0         350.0        560.0        250.0       400.0
185          4            8            1536         350.0        470.0          350.0         400.0         350.0        550.0        250.0       400.0
186          4            8            1536         350.0        460.0          350.0         400.0         350.0        540.0        250.0       400.0
187          4            8            1536         350.0        450.0          350.0         400.0         350.0        530.0        250.0       400.0
188          4            8            1536         350.0        450.0          350.0         400.0         350.0        520.0        250.0       400.0
189          4            8            1536         350.0        450.0          350.0         400.0         350.0        510.0        250.0       400.0
190          4            8            1536         350.0        450.0          350.0         400.0         350.0        500.0        250.0       400.0
191          4            7            1344         300.0        650.0          300.0         600.0         300.0        700.0        250.0       350.0
192          4            7            1344         300.0        640.0          300.0         590.0         300.0        690.0        250.0       350.0
193          4            7            1344         300.0        630.0          300.0         580.0         300.0        680.0        250.0       350.0
194          4            7            1344         300.0        620.0          300.0         570.0         300.0        670.0        250.0       350.0
195          4            7            1344         300.0        610.0          300.0         560.0         300.0        660.0        250.0       350.0
196          4            7            1344         300.0        600.0          300.0         550.0         300.0        650.0        250.0       350.0
197          4            7            1344         300.0        590.0          300.0         540.0         300.0        640.0        250.0       350.0
198          4            7            1344         300.0        580.0          300.0         530.0         300.0        630.0        250.0       350.0
199          4            7            1344         300.0        570.0          300.0         520.0         300.0        620.0        250.0       350.0
200          4            7            1344         300.0        560.0          300.0         510.0         300.0        610.0        250.0       350.0
201          4            7            1344         300.0        550.0          300.0         500.0         300.0        600.0        250.0       350.0
202          4            6            1152         350.0        450.0          350.0         380.0         350.0        500.0        250.0       400.0
203          4            5             960         350.0        450.0          350.0         400.0         350.0        500.0        250.0       400.0
204          4            5             960         350.0        440.0          350.0         390.0         350.0        490.0        250.0       400.0
205          4            5             960         350.0        430.0          350.0         380.0         350.0        480.0        250.0       400.0

In [19]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

# Load the dataset
data = dataset

df = pd.DataFrame(data)

# Split the dataset into input features and target variables
X = df[['Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)', 'Outer height', 'Outer width']]
y_corner_height = df['Corner height']
y_corner_width = df['Corner width']
y_inner_height = df['Inner height']
y_inner_width = df['Inner width']
y_outer_height = df['Outer height']
y_outer_width = df['Outer width']
y_beam_height = df['Beam height']
y_beam_width = df['Beam width']

# Create and train the SVR models for each dimension
svr_corner_height = SVR()
svr_corner_height.fit(X, y_corner_height)

svr_corner_width = SVR()
svr_corner_width.fit(X, y_corner_width)

svr_inner_height = SVR()
svr_inner_height.fit(X, y_inner_height)

svr_inner_width = SVR()
svr_inner_width.fit(X, y_inner_width)

svr_outer_height = SVR()
svr_outer_height.fit(X, y_outer_height)

svr_outer_width = SVR()
svr_outer_width.fit(X, y_outer_width)

svr_beam_height = SVR()
svr_beam_height.fit(X, y_beam_height)

svr_beam_width = SVR()
svr_beam_width.fit(X, y_beam_width)

# Create a dataframe with the input values for prediction
input_data = pd.DataFrame({
    'Span(i/p)': [3],
    'Storey(i/p)': [9],
    'Area(sqm)(i/p)': [1296],
    'Outer height': [0.0],
    'Outer width': [0.0]
})

# Predict the dimensions
corner_height_prediction = svr_corner_height.predict(input_data)
corner_width_prediction = svr_corner_width.predict(input_data)
inner_height_prediction = svr_inner_height.predict(input_data)
inner_width_prediction = svr_inner_width.predict(input_data)
outer_height_prediction = svr_outer_height.predict(input_data)
outer_width_prediction = svr_outer_width.predict(input_data)
beam_height_prediction = svr_beam_height.predict(input_data)
beam_width_prediction = svr_beam_width.predict(input_data)

# Print the predicted dimensions
print("L shape:- ")
print("Inner Dimension: {}x{}".format(round(inner_height_prediction[0]), round(inner_width_prediction[0])))
print("Outer Dimension: {}x{}".format(round(outer_height_prediction[0]), round(outer_width_prediction[0])))
print("Corner Dimension: {}x{}".format(round(corner_height_prediction[0]), round(corner_width_prediction[0])))
print("Beam Dimension: {}x{}".format(round(beam_height_prediction[0]), round(beam_width_prediction[0])))

L shape:-
Inner Dimension: 350x530
Outer Dimension: 350x471
Corner Dimension: 350x398
Beam Dimension: 250x376

In [558]:


#print("train score : " , model.score(X_train,y_train))
#print("test score : " , model.score(X_test,y_test))

# C SHAPE

In [2]:
#Importing dataset : 
dataset=pd.read_csv("C.csv")
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x350,300x400,300x450,250x250,3,2,432
1,300x300,300x300,300x300,250x250,3,2,432
2,300x340,300x390,300x440,250x250,3,2,432
3,300x330,300x380,300x430,250x250,3,2,432
4,300x320,300x370,300x420,250x250,3,2,432
...,...,...,...,...,...,...,...
319,380x750,380x780,380x780,250x450,5,9,2700
320,380x750,380x770,380x770,250x450,5,9,2700
321,380x750,380x760,380x760,250x450,5,9,2700
322,380x750,380x750,380x750,250x450,5,9,2700
323,380x750,380x740,380x740,250x450,5,9,2700

In [3]:
#  FINDING NULL VALUES IN THE DATASET
print ( "NULL VALUES : \n" , dataset . isnull())

NULL VALUES :
      Corner column(o/p)  Outer column(o/p)  Inner Column(o/p)  Beam(o/p)  \
0                 False              False              False      False
1                 False              False              False      False
2                 False              False              False      False
3                 False              False              False      False
4                 False              False              False      False
..                  ...                ...                ...        ...
319               False              False              False      False
320               False              False              False      False
321               False              False              False      False
322               False              False              False      False
323               False              False              False      False

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
0        False        False           False
1        False        False           False
2        False        False           False
3        False        False           False
4        False        False           False
..         ...          ...             ...
319      False        False           False
320      False        False           False
321      False        False           False
322      False        False           False
323      False        False           False

[324 rows x 7 columns]

In [4]:
#dropping duplicate values
dataset.drop_duplicates(inplace=True)
print(dataset.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
318    False
319    False
320    False
321    False
323    False
Length: 318, dtype: bool

In [5]:
dataset.isnull().sum()

Corner column(o/p)    0
Outer column(o/p)     0
Inner Column(o/p)     0
Beam(o/p)             0
Span(i/p)             0
Storey(i/p)           0
Area(sqm)(i/p)        0
dtype: int64

In [6]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame


# Split the column into separate integer columns
dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Outer column(o/p)', axis=1, inplace=True)

In [7]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame


# Split the column into separate integer columns
dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Corner column(o/p)', axis=1, inplace=True)

In [8]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values


# Split the column into separate integer columns
dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Inner Column(o/p)', axis=1, inplace=True)

C:\Users\Atees\AppData\Local\Temp\ipykernel_1544\794543552.py:16: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [9]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('x')  # Use 'x' as the separator
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values


# Split the column into separate integer columns
dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Beam(o/p)', axis=1, inplace=True)

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

dataset.fillna(0, inplace=True)

# Split the dataset into input features and target variables
X = dataset[['Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)']]
y = dataset[['Inner height', 'Inner width', 'Outer height', 'Outer width', 'Corner height', 'Corner width', 'Beam height', 'Beam width']]

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the mean squared error (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Predict dimensions for new data
new_data = {
    'Span(i/p)': [3],
    'Storey(i/p)': [6],
    'Area(sqm)(i/p)': [1296],
}
new_df = pd.DataFrame(new_data)

predicted_dimensions = model.predict(new_df)
inner_dim = predicted_dimensions[0][:2].astype(int)
outer_dim = predicted_dimensions[0][2:4].astype(int)
corner_dim = predicted_dimensions[0][4:6].astype(int)
beam_dim = predicted_dimensions[0][6:].astype(int)

print("C shape:-")
print(f"Inner Dimension: {max(inner_dim[0], 250)}x{max(inner_dim[1], 250)}")
print(f"Outer Dimension: {max(outer_dim[0], 250)}x{max(outer_dim[1], 250)}")
print(f"Corner Dimension: {max(corner_dim[0], 250)}x{max(corner_dim[1], 250)}")
print(f"Beam Dimension: {max(beam_dim[0], 250)}x{max(beam_dim[1], 250)}")

Mean Squared Error: 3907.47806408664
C shape:-
Inner Dimension: 304x515
Outer Dimension: 305x461
Corner Dimension: 304x421
Beam Dimension: 250x292

In [779]:


print("train score : " , model.score(X_train,y_train))
print("test score : " , model.score(X_test,y_test))

train score :  0.7690900737345971
test score :  0.6784536055154198

In [122]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
0,3,2,432,300,400,300,350,300.0,450.0,250,250
1,3,2,432,300,300,300,300,300.0,300.0,250,250
2,3,2,432,300,390,300,340,300.0,440.0,250,250
3,3,2,432,300,380,300,330,300.0,430.0,250,250
4,3,2,432,300,370,300,320,300.0,420.0,250,250
...,...,...,...,...,...,...,...,...,...,...,...
318,5,9,2700,380,790,380,740,380.0,790.0,250,450
319,5,9,2700,380,780,380,750,380.0,780.0,250,450
320,5,9,2700,380,770,380,750,380.0,770.0,250,450
321,5,9,2700,380,760,380,750,380.0,760.0,250,450
323,5,9,2700,380,740,380,750,380.0,740.0,250,450

# T SHAPE

In [74]:

dataset=pd.read_csv("T.csv")
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,350X700,350X720,350X750,250X300,3,9,1053
1,350X700,350X720,350X750,250X400,4,9,1440
2,350X690,350X710,350X740,250X400,4,9,1440
3,350X680,350X700,350X730,250X400,4,9,1440
4,350X670,350X690,350X720,250X400,4,9,1440
...,...,...,...,...,...,...,...
356,300X350,300X350,300X370,250X350,4,2,320
357,300X350,300X350,300X360,250X350,4,2,320
358,300X350,300X350,300X350,250X350,4,2,320
359,300x350,300x350,300x350,250x350,4,2,320
360,350X450,350X500,350X550,250x300,5,2,500

In [75]:
#  FINDING NULL VALUES IN THE DATASET
print ( "NULL VALUES : \n" , dataset . isnull())

NULL VALUES :
      Corner column(o/p)  Outer column(o/p)  Inner Column(o/p)  Beam(o/p)  \
0                 False              False              False      False
1                 False              False              False      False
2                 False              False              False      False
3                 False              False              False      False
4                 False              False              False      False
..                  ...                ...                ...        ...
356               False              False              False      False
357               False              False              False      False
358               False              False              False      False
359               False              False              False      False
360               False              False              False      False

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
0        False        False           False
1        False        False           False
2        False        False           False
3        False        False           False
4        False        False           False
..         ...          ...             ...
356      False        False           False
357      False        False           False
358      False        False           False
359      False        False           False
360      False        False           False

[361 rows x 7 columns]

In [76]:
#dropping duplicate values
dataset.drop_duplicates(inplace=True)
print(dataset.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
356    False
357    False
358    False
359    False
360    False
Length: 306, dtype: bool

In [77]:
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,350X700,350X720,350X750,250X300,3,9,1053
1,350X700,350X720,350X750,250X400,4,9,1440
2,350X690,350X710,350X740,250X400,4,9,1440
3,350X680,350X700,350X730,250X400,4,9,1440
4,350X670,350X690,350X720,250X400,4,9,1440
...,...,...,...,...,...,...,...
356,300X350,300X350,300X370,250X350,4,2,320
357,300X350,300X350,300X360,250X350,4,2,320
358,300X350,300X350,300X350,250X350,4,2,320
359,300x350,300x350,300x350,250x350,4,2,320
360,350X450,350X500,350X550,250x300,5,2,500

In [78]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Corner column(o/p)', axis=1, inplace=True)

print(dataset)

    Outer column(o/p) Inner Column(o/p) Beam(o/p)  Span(i/p)  Storey(i/p)  \
0             350X720           350X750   250X300          3            9
1             350X720           350X750   250X400          4            9
2             350X710           350X740   250X400          4            9
3             350X700           350X730   250X400          4            9
4             350X690           350X720   250X400          4            9
..                ...               ...       ...        ...          ...
356           300X350           300X370   250X350          4            2
357           300X350           300X360   250X350          4            2
358           300X350           300X350   250X350          4            2
359           300x350           300x350   250x350          4            2
360           350X500           350X550   250x300          5            2

     Area(sqm)(i/p)  Corner height  Corner width
0              1053          350.0         700.0
1              1440          350.0         700.0
2              1440          350.0         690.0
3              1440          350.0         680.0
4              1440          350.0         670.0
..              ...            ...           ...
356             320          300.0         350.0
357             320          300.0         350.0
358             320          300.0         350.0
359             320            NaN           NaN
360             500          350.0         450.0

[306 rows x 8 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\519432503.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [79]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Outer column(o/p)', axis=1, inplace=True)

print(dataset)

    Inner Column(o/p) Beam(o/p)  Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  \
0             350X750   250X300          3            9            1053
1             350X750   250X400          4            9            1440
2             350X740   250X400          4            9            1440
3             350X730   250X400          4            9            1440
4             350X720   250X400          4            9            1440
..                ...       ...        ...          ...             ...
356           300X370   250X350          4            2             320
357           300X360   250X350          4            2             320
358           300X350   250X350          4            2             320
359           300x350   250x350          4            2             320
360           350X550   250x300          5            2             500

     Corner height  Corner width  Outer height  Outer width
0            350.0         700.0         350.0        720.0
1            350.0         700.0         350.0        720.0
2            350.0         690.0         350.0        710.0
3            350.0         680.0         350.0        700.0
4            350.0         670.0         350.0        690.0
..             ...           ...           ...          ...
356          300.0         350.0         300.0        350.0
357          300.0         350.0         300.0        350.0
358          300.0         350.0         300.0        350.0
359            NaN           NaN           NaN          NaN
360          350.0         450.0         350.0        500.0

[306 rows x 9 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\3711316056.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [80]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Inner Column(o/p)', axis=1, inplace=True)

print(dataset)

    Beam(o/p)  Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Corner height  \
0     250X300          3            9            1053          350.0
1     250X400          4            9            1440          350.0
2     250X400          4            9            1440          350.0
3     250X400          4            9            1440          350.0
4     250X400          4            9            1440          350.0
..        ...        ...          ...             ...            ...
356   250X350          4            2             320          300.0
357   250X350          4            2             320          300.0
358   250X350          4            2             320          300.0
359   250x350          4            2             320            NaN
360   250x300          5            2             500          350.0

     Corner width  Outer height  Outer width  Inner height  Inner width
0           700.0         350.0        720.0         350.0        750.0
1           700.0         350.0        720.0         350.0        750.0
2           690.0         350.0        710.0         350.0        740.0
3           680.0         350.0        700.0         350.0        730.0
4           670.0         350.0        690.0         350.0        720.0
..            ...           ...          ...           ...          ...
356         350.0         300.0        350.0         300.0        370.0
357         350.0         300.0        350.0         300.0        360.0
358         350.0         300.0        350.0         300.0        350.0
359           NaN           NaN          NaN           NaN          NaN
360         450.0         350.0        500.0         350.0        550.0

[306 rows x 10 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\4116055036.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [81]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Beam(o/p)', axis=1, inplace=True)

print(dataset)

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Corner height  Corner width  \
0            3            9            1053          350.0         700.0
1            4            9            1440          350.0         700.0
2            4            9            1440          350.0         690.0
3            4            9            1440          350.0         680.0
4            4            9            1440          350.0         670.0
..         ...          ...             ...            ...           ...
356          4            2             320          300.0         350.0
357          4            2             320          300.0         350.0
358          4            2             320          300.0         350.0
359          4            2             320            NaN           NaN
360          5            2             500          350.0         450.0

     Outer height  Outer width  Inner height  Inner width  Beam height  \
0           350.0        720.0         350.0        750.0        250.0
1           350.0        720.0         350.0        750.0        250.0
2           350.0        710.0         350.0        740.0        250.0
3           350.0        700.0         350.0        730.0        250.0
4           350.0        690.0         350.0        720.0        250.0
..            ...          ...           ...          ...          ...
356         300.0        350.0         300.0        370.0        250.0
357         300.0        350.0         300.0        360.0        250.0
358         300.0        350.0         300.0        350.0        250.0
359           NaN          NaN           NaN          NaN          NaN
360         350.0        500.0         350.0        550.0          NaN

     Beam width
0         300.0
1         400.0
2         400.0
3         400.0
4         400.0
..          ...
356       350.0
357       350.0
358       350.0
359         NaN
360         NaN

[306 rows x 11 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\2830076836.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

In [82]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Corner height,Corner width,Outer height,Outer width,Inner height,Inner width,Beam height,Beam width
0,3,9,1053,350.0,700.0,350.0,720.0,350.0,750.0,250.0,300.0
1,4,9,1440,350.0,700.0,350.0,720.0,350.0,750.0,250.0,400.0
2,4,9,1440,350.0,690.0,350.0,710.0,350.0,740.0,250.0,400.0
3,4,9,1440,350.0,680.0,350.0,700.0,350.0,730.0,250.0,400.0
4,4,9,1440,350.0,670.0,350.0,690.0,350.0,720.0,250.0,400.0
...,...,...,...,...,...,...,...,...,...,...,...
356,4,2,320,300.0,350.0,300.0,350.0,300.0,370.0,250.0,350.0
357,4,2,320,300.0,350.0,300.0,350.0,300.0,360.0,250.0,350.0
358,4,2,320,300.0,350.0,300.0,350.0,300.0,350.0,250.0,350.0
359,4,2,320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,5,2,500,350.0,450.0,350.0,500.0,350.0,550.0,NaN,NaN

In [83]:
dataset.dropna(inplace=True)

In [84]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Split the dataset into input features and target variables
X = dataset[['Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)']]
y = dataset[['Inner height', 'Inner width', 'Outer height', 'Outer width', 'Corner height', 'Corner width', 'Beam height', 'Beam width']]

# Train the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict dimensions for new data
new_data = {
    'Span(i/p)': [3],
    'Storey(i/p)': [9],
    'Area(sqm)(i/p)': [1053],
}
new_df = pd.DataFrame(new_data)

predicted_dimensions = model.predict(new_df)
inner_dim = predicted_dimensions[0][:2].astype(int)
outer_dim = predicted_dimensions[0][2:4].astype(int)
corner_dim = predicted_dimensions[0][4:6].astype(int)
beam_dim = predicted_dimensions[0][6:].astype(int)

print("T shape:-")
print(f"Inner Dimension: {max(inner_dim[0], 250)}x{max(inner_dim[1], 250)}")
print(f"Outer Dimension: {max(outer_dim[0], 250)}x{max(outer_dim[1], 250)}")
print(f"Corner Dimension: {max(corner_dim[0], 250)}x{max(corner_dim[1], 250)}")
print(f"Beam Dimension: {max(beam_dim[0], 250)}x{max(beam_dim[1], 250)}")

T shape:-
Inner Dimension: 340x621
Outer Dimension: 340x603
Corner Dimension: 340x580
Beam Dimension: 250x324

In [791]:
print("train score : " , model.score(X_train,y_train))
print("test score : " , model.score(X_test,y_test))

train score :  0.5459878090076531
test score :  0.4808291175105342

# I SHAPE

In [99]:

dataset=pd.read_csv("I.csv")
dataset

,Corner column(o/p),Outer column(o/p),Inner Column(o/p),Beam(o/p),Span(i/p),Storey(i/p),Area(sqm)(i/p)
0,300x300,300x350,300x450,250x300,3,4,684
1,300x300,300x350,300x450,250x300,3,4,684
2,300X300,300X340,300x450,250x300,3,4,684
3,300X300,300X330,300x450,250x300,3,4,684
4,300X300,300X320,300x450,250x300,3,4,684
...,...,...,...,...,...,...,...
625,300X340,300X340,300X340,250X350,4,2,384
626,300X330,300X330,300X330,250x350,4,2,384
627,300X320,300X320,300X320,250X350,4,2,384
628,300X310,300X310,300X310,250X350,4,2,384
629,300X300,300X300,300X300,250x350,4,2,384

In [100]:
#  FINDING NULL VALUES IN THE DATASET
print ( "NULL VALUES : \n" , dataset . isnull())

NULL VALUES :
      Corner column(o/p)  Outer column(o/p)  Inner Column(o/p)  Beam(o/p)  \
0                 False              False              False      False
1                 False              False              False      False
2                 False              False              False      False
3                 False              False              False      False
4                 False              False              False      False
..                  ...                ...                ...        ...
625               False              False              False      False
626               False              False              False      False
627               False              False              False      False
628               False              False              False      False
629               False              False              False      False

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)
0        False        False           False
1        False        False           False
2        False        False           False
3        False        False           False
4        False        False           False
..         ...          ...             ...
625      False        False           False
626      False        False           False
627      False        False           False
628      False        False           False
629      False        False           False

[630 rows x 7 columns]

In [101]:
#dropping duplicate values
dataset.drop_duplicates(inplace=True)
print(dataset.duplicated())

0      False
2      False
3      False
4      False
5      False
       ...
310    False
311    False
312    False
313    False
314    False
Length: 312, dtype: bool

In [102]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Outer column(o/p)', axis=1, inplace=True)

print(dataset)

    Corner column(o/p) Inner Column(o/p) Beam(o/p)  Span(i/p)  Storey(i/p)  \
0              300x300           300x450   250x300          3            4
2              300X300           300x450   250x300          3            4
3              300X300           300x450   250x300          3            4
4              300X300           300x450   250x300          3            4
5              300X300           300x450   250x300          3            4
..                 ...               ...       ...        ...          ...
310            300X340           300X340   250X350          4            2
311            300X330           300X330   250x350          4            2
312            300X320           300X320   250X350          4            2
313            300X310           300X310   250X350          4            2
314            300X300           300X300   250x350          4            2

     Area(sqm)(i/p)  Outer height  Outer width
0               684           NaN          NaN
2               684         300.0        340.0
3               684         300.0        330.0
4               684         300.0        320.0
5               684         300.0        310.0
..              ...           ...          ...
310             384         300.0        340.0
311             384         300.0        330.0
312             384         300.0        320.0
313             384         300.0        310.0
314             384         300.0        300.0

[312 rows x 8 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\3711316056.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Outer height', 'Outer width']] = dataset['Outer column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [103]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Corner column(o/p)', axis=1, inplace=True)

print(dataset)

    Inner Column(o/p) Beam(o/p)  Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  \
0             300x450   250x300          3            4             684
2             300x450   250x300          3            4             684
3             300x450   250x300          3            4             684
4             300x450   250x300          3            4             684
5             300x450   250x300          3            4             684
..                ...       ...        ...          ...             ...
310           300X340   250X350          4            2             384
311           300X330   250x350          4            2             384
312           300X320   250X350          4            2             384
313           300X310   250X350          4            2             384
314           300X300   250x350          4            2             384

     Outer height  Outer width  Corner height  Corner width
0             NaN          NaN            NaN           NaN
2           300.0        340.0          300.0         300.0
3           300.0        330.0          300.0         300.0
4           300.0        320.0          300.0         300.0
5           300.0        310.0          300.0         300.0
..            ...          ...            ...           ...
310         300.0        340.0          300.0         340.0
311         300.0        330.0          300.0         330.0
312         300.0        320.0          300.0         320.0
313         300.0        310.0          300.0         310.0
314         300.0        300.0          300.0         300.0

[312 rows x 9 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\519432503.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Corner height', 'Corner width']] = dataset['Corner column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [104]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Inner Column(o/p)', axis=1, inplace=True)

print(dataset)

    Beam(o/p)  Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Outer height  \
0     250x300          3            4             684           NaN
2     250x300          3            4             684         300.0
3     250x300          3            4             684         300.0
4     250x300          3            4             684         300.0
5     250x300          3            4             684         300.0
..        ...        ...          ...             ...           ...
310   250X350          4            2             384         300.0
311   250x350          4            2             384         300.0
312   250X350          4            2             384         300.0
313   250X350          4            2             384         300.0
314   250x350          4            2             384         300.0

     Outer width  Corner height  Corner width  Inner height  Inner width
0            NaN            NaN           NaN           NaN          NaN
2          340.0          300.0         300.0           NaN          NaN
3          330.0          300.0         300.0           NaN          NaN
4          320.0          300.0         300.0           NaN          NaN
5          310.0          300.0         300.0           NaN          NaN
..           ...            ...           ...           ...          ...
310        340.0          300.0         340.0         300.0        340.0
311        330.0          300.0         330.0         300.0        330.0
312        320.0          300.0         320.0         300.0        320.0
313        310.0          300.0         310.0         300.0        310.0
314        300.0          300.0         300.0         300.0        300.0

[312 rows x 10 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\4116055036.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Inner height', 'Inner width']] = dataset['Inner Column(o/p)'].apply(convert_to_int).apply(pd.Series)

In [105]:
import pandas as pd

def convert_to_int(value):
    numbers = value.split('X')  # Use 'X' as the separator (capital 'X')
    integer_values = []
    for num in numbers:
        try:
            num_int = int(num)
            integer_values.append(num_int)
        except ValueError:
            pass  # Skip non-numeric values
    return integer_values

# Load the dataset into a Pandas DataFrame
data = dataset

dataset = pd.DataFrame(data)

# Split the column into separate integer columns
dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

# Drop the original column if needed
dataset.drop('Beam(o/p)', axis=1, inplace=True)

print(dataset)

     Span(i/p)  Storey(i/p)  Area(sqm)(i/p)  Outer height  Outer width  \
0            3            4             684           NaN          NaN
2            3            4             684         300.0        340.0
3            3            4             684         300.0        330.0
4            3            4             684         300.0        320.0
5            3            4             684         300.0        310.0
..         ...          ...             ...           ...          ...
310          4            2             384         300.0        340.0
311          4            2             384         300.0        330.0
312          4            2             384         300.0        320.0
313          4            2             384         300.0        310.0
314          4            2             384         300.0        300.0

     Corner height  Corner width  Inner height  Inner width  Beam height  \
0              NaN           NaN           NaN          NaN          NaN
2            300.0         300.0           NaN          NaN          NaN
3            300.0         300.0           NaN          NaN          NaN
4            300.0         300.0           NaN          NaN          NaN
5            300.0         300.0           NaN          NaN          NaN
..             ...           ...           ...          ...          ...
310          300.0         340.0         300.0        340.0        250.0
311          300.0         330.0         300.0        330.0          NaN
312          300.0         320.0         300.0        320.0        250.0
313          300.0         310.0         300.0        310.0        250.0
314          300.0         300.0         300.0        300.0          NaN

     Beam width
0           NaN
2           NaN
3           NaN
4           NaN
5           NaN
..          ...
310       350.0
311         NaN
312       350.0
313       350.0
314         NaN

[312 rows x 11 columns]

C:\Users\Atees\AppData\Local\Temp\ipykernel_8640\2830076836.py:20: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dataset[['Beam height', 'Beam width']] = dataset['Beam(o/p)'].apply(convert_to_int).apply(pd.Series)

In [106]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
0,3,4,684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,4,684,300.0,340.0,300.0,300.0,NaN,NaN,NaN,NaN
3,3,4,684,300.0,330.0,300.0,300.0,NaN,NaN,NaN,NaN
4,3,4,684,300.0,320.0,300.0,300.0,NaN,NaN,NaN,NaN
5,3,4,684,300.0,310.0,300.0,300.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
310,4,2,384,300.0,340.0,300.0,340.0,300.0,340.0,250.0,350.0
311,4,2,384,300.0,330.0,300.0,330.0,300.0,330.0,NaN,NaN
312,4,2,384,300.0,320.0,300.0,320.0,300.0,320.0,250.0,350.0
313,4,2,384,300.0,310.0,300.0,310.0,300.0,310.0,250.0,350.0
314,4,2,384,300.0,300.0,300.0,300.0,300.0,300.0,NaN,NaN

In [107]:
dataset.dropna(inplace=True)

In [108]:
dataset

,Span(i/p),Storey(i/p),Area(sqm)(i/p),Outer height,Outer width,Corner height,Corner width,Inner height,Inner width,Beam height,Beam width
16,3,4,684,300.0,300.0,300.0,300.0,300.0,310.0,350.0,300.0
142,3,9,1539,350.0,650.0,350.0,600.0,350.0,700.0,250.0,300.0
143,3,9,1539,350.0,650.0,350.0,590.0,350.0,690.0,250.0,300.0
144,3,9,1539,350.0,650.0,350.0,580.0,350.0,680.0,250.0,300.0
145,3,9,1539,350.0,650.0,350.0,570.0,350.0,680.0,250.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...
297,3,2,342,300.0,300.0,300.0,300.0,300.0,310.0,250.0,250.0
298,3,2,342,300.0,300.0,300.0,300.0,300.0,300.0,250.0,250.0
310,4,2,384,300.0,340.0,300.0,340.0,300.0,340.0,250.0,350.0
312,4,2,384,300.0,320.0,300.0,320.0,300.0,320.0,250.0,350.0
313,4,2,384,300.0,310.0,300.0,310.0,300.0,310.0,250.0,350.0

In [112]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Split the dataset into input features and target variables
X = dataset[['Span(i/p)', 'Storey(i/p)', 'Area(sqm)(i/p)']]
y = dataset[['Inner height', 'Inner width', 'Outer height', 'Outer width', 'Corner height', 'Corner width', 'Beam height', 'Beam width']]

# Train the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict dimensions for new data
new_data = {
    'Span(i/p)': [3],
    'Storey(i/p)': [9],
    'Area(sqm)(i/p)': [1053],
}
new_df = pd.DataFrame(new_data)

predicted_dimensions = model.predict(new_df)
inner_dim = predicted_dimensions[0][:2].astype(int)
outer_dim = predicted_dimensions[0][2:4].astype(int)
corner_dim = predicted_dimensions[0][4:6].astype(int)
beam_dim = predicted_dimensions[0][6:].astype(int)

print("I shape:-")
print(f"Inner Dimension: {inner_dim[0]}x{inner_dim[1]}")
print(f"Outer Dimension: {outer_dim[0]}x{outer_dim[1]}")
print(f"Corner Dimension: {corner_dim[0]}x{corner_dim[1]}")
print(f"Beam Dimension: {beam_dim[0]}x{beam_dim[1]}")

I shape:-
Inner Dimension: 338x655
Outer Dimension: 338x627
Corner Dimension: 338x437
Beam Dimension: 247x291